name: StockAnalysisAPI_CD

on:
  workflow_run:
    workflows: ["StockAnalysisAPI_CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checkout Github Repository'
        uses: actions/checkout@v2

      - name: 'Login and Copy project via SSH on Remote Server'
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_ADDR }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PWD }}
          port: ${{ secrets.SERVER_PORT }}
          source: "./*"
          target: "/home/stockmarketanalysis/dockers/StockAnalysisAPI/service"

      - name: 'Deploy docker via SSH on Remote Server'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_ADDR }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PWD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            # Docker로 서비스 빌드 및 실행
            cd ~/dockers/StockAnalysisAPI/service
            docker build -t docker:StockAnalysisAPI_service .
            docker stop StockAnalysisAPI_service || true
            docker rm StockAnalysisAPI_service || true
            docker run -d --name StockAnalysisAPI_service docker:StockAnalysisAPI_service
