name: StockAnalysisAPI_CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - name: 'Checkout Github Repository'
        uses: actions/checkout@v2

      - name: 'Login and Copy project via SSH on Remote Server'
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_ADDR }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PWD }}
          port: ${{ secrets.SERVER_PORT }}
          ssh_option: "-o StrictHostKeyChecking=no"
          source: "./*"
          target: "/home/stockmarketanalysis/dockers/StockAnalysisAPI/service"

      - name: 'Deploy docker via SSH on Remote Server'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_ADDR }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PWD }}
          port: ${{ secrets.SERVER_PORT }}
          ssh_option: "-o StrictHostKeyChecking=no"
          script: |
            # Docker로 서비스 빌드 및 실행
            cd ~/dockers/StockAnalysisAPI/service
            docker stop StockAnalysisAPI_service || true
            docker rm StockAnalysisAPI_service || true
            docker build -t docker:StockAnalysisAPI_service .
            docker run -d --name StockAnalysisAPI_service docker:StockAnalysisAPI_service
            # 도커 네트워크 연결
            docker network connect socket_net StockAnalysisAPI_service
